version: "3.7"
services:
  app-gametrack:
    build: .
    depends_on:
        postgres2:
          condition: service_healthy

    container_name: "gametrack"
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_DATABASE=dbtest
      - DB_USERNAME=test
      - DB_PASSWORD=test


  postgres2:
    image: postgres
    container_name: "postgres2"
    volumes:
      - ./postgres:/var/lib/postgres
    environment:
      - POSTGRES_DB=dbtest
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]




