# Nome da pipelina
name: CI-CD

#Qual o trigger que será escutado para rodar a pipeline
on:
  #Informa qual o/os evento(s)
  push:
  #Informa qual a/as branch(es)
    branches: ["main"]
  #Permite executar a pipeline manualmente
  workflow_dispatch:

#Informa quais serão os jobs/processos da pipeline
jobs:
  #Nomeia o job
  build-game-api:
    #Informa em qual anbiente rodará o job
    runs-on: ubuntu-latest
    #Informa quais será os passos do job
    steps:
        #Informa qual o nome e o que o passo irá fazer
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven
      - name: Build and test Game-API with Maven
        run: mvn -f gametracker-api/ --batch-mode package
      - name: Copy artifact to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PWD }}
          port: ${{ secrets.VPS_PORT }}
          source: 'gametracker-api/target/gametracker-hexagonal-v.jar'
          target: '/home'
          strip_components: 2
        
  deploy-heroku:
    needs: [build-game-api]
    #Informa em qual anbiente rodará o job
    runs-on: ubuntu-latest
    #Informa quais será os passos do job
    steps:
        #Informa qual o nome e o que o passo irá fazer
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Connect and deploy in Heroku
        uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "gametracker-game-api" #Must be unique in Heroku
          heroku_email: "brunoandreotti@outlook.com"
          appdir: "gametracker-api"

